version: '3'

services:
  master:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
     - "8089:8089"
    volumes:
      - ./code:/mnt/locust/
    command: -f /mnt/locust/locustfile.py --master -H https://www.google.it

  worker:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./code:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master